# Generated by Django 3.1.5 on 2021-02-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlace',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
    ]
